// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pedidos.Data.Context;

#nullable disable

namespace Pedidos.Data.Migrations
{
    [DbContext(typeof(PedidoContext))]
    partial class PedidoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pedidos.Domain.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<DateTime>("DataHorarioAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHorarioCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataHorarioExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int(10) unsigned");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int(10) unsigned");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItensPedido", (string)null);
                });

            modelBuilder.Entity("Pedidos.Domain.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<DateTime>("DataHorarioAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHorarioCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataHorarioExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int(10) unsigned");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("Pedidos.Domain.Models.ItemPedido", b =>
                {
                    b.HasOne("Pedidos.Domain.Models.Pedido", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Pedidos.Domain.Models.Pedido", b =>
                {
                    b.Navigation("ItensPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
